name: CastleWars
main: org.mcdynasty.castlewars.CastleWars
description: A Fun mini-game, inspired by RuneScape.
author: PixelCrumbs
version: 1.0
commands:
   join:
      description: Join a team.
      usage: Use /help for a list of valid commands.
   info:
      description: Join a team.
      usage: /<command>