name: CastleWars
main: org.mcdynasty.castlewars.CastleWars
description: A Fun mini-game, inspired by RuneScape.
author: PixelCrumbs
version: 1.0
commands:
   join:
      description: Join a team.
      # removed the usage section - it'll only cause you problems in the long run.
   info:
      description: Join a team.
      # same thing here.
